id: error_notification
namespace: company.team

triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: company.team
        prefix: true
    disabled: true

tasks:
  - id: send_mail
    type: io.kestra.plugin.email.MailSend
    to: day811@laposte.net
    subject: "🔴 ocde_p10 FAILED: {{ trigger.executionId }}"
    host: "{{ secret('SMTP_HOST') }}"
    transportStrategy: SMTP_TLS
    password: "{{ secret('SMTP_PASSWORD') }}"
    username: "{{ secret('SMTP_USER') }}"
    port: "587"
    htmlTextContent: |-
      <body><title>Pipeline ocde_p10 a échoué!</title>
      <p>Execution: {{ trigger.executionId }}</p>
      <p>Voir les logs pour plus de détails</p>
      </body>
    from: day811@laposte.net
    plainTextContent: |-
      Pipeline ocde_p10 a échoué!
      Execution: {{ trigger.executionId }}
      Voir les logs pour plus de détails
